
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-setup-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup-go
        id: setup-go
        uses: ./
      - run: |
          echo ${{ steps.setup-go.outputs.go-path }}
          echo ${{ steps.setup-go.outputs.go-root }}
          echo ${{ steps.setup-go.outputs.go-mod }}
          echo ${{ steps.setup-go.outputs.go-mod-cache }}
          echo ${{ steps.setup-go.outputs.go-env }}
          echo ${{ steps.setup-go.outputs.cache-hit }}
          echo ${{ steps.setup-go.outputs.go-version }}
